server:
  port: 8081
  servlet:
    context-path: /employee-svc

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employeedb
    username: devuser
    password: devuser@pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true