server:
  port: 8081
  servlet:
    context-path: /employee-svc

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employeedb
    username: devuser
    password: devuser@pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: ems-employee-service
  config:
    import: optional:configserver:http://localhost:8082

  cache:
    type: redis
    host: localhost
    port: 6379
    redis:
      cache-null-value: true
      time-to-live: 40000